### ISSUE TITLE
Iso generation Commands with cli tools like mkisofs (or xorriso)

### ISSUE THREAD

**Issue by aadi58002** [memstechtips/UnattendedWinstall#10]
Current Iso modifying steps do not include any way to create a Iso on a Linux system. Anyburn a window only program.

A generic way to create a iso on a linux system should be added to the README.
The common iso tools which were readily available were mkisofs, genisoimage and xorriso. There might be easier GUI solution as well of which I am not aware.

Thanks for the work of maintaining this repo.

**Comment by memstechtips** [comment]
Hi I haven't thought of that, it might be something I will look into in the future. Thanks for the suggestion.
