### ISSUE TITLE
Lenovo ThinkPad E16 G1 laggs and then overheats

### ISSUE THREAD

**Issue by Matyanson** [memstechtips/UnattendedWinstall#100]
1) Created bootable usb with Win11 using the official MediaCreationTool_Win11_23H2.exe
2) Downloaded the [Standard](https://github.com/memstechtips/UnattendedWinstall/blob/main/Standard/autounattend.xml) autounattend.xml file, removed calculator, camera and paint from the uninstall list and pasted it into the usb root directory
3) Booted from the Windows Installation USB

During the whole process, the notebook did not have access to the internet and I plugged in a mouse, which worked correctly. The installation went as expected.
First, I check how much memory was taken. It was about 18GB which is an improvement from the before ~55GB. When operating the notebook, I think it was slightly laggy (but not sure). I also noticed I could not search for wifi and no speaker or microphone device was found. Maybe drivers are missing?
Then I tried running the "LAUNCH-CTT-WINUTIL" script. It flashed briefly with some error message.
I left the device on for about 10-15 minutes. The fan was on and louder and louder (I did not notice since I had headphones). When I returned the laptop was extremely hot and the fan was loud (turning off and then on full power). Before I could turn off the device manually, it shut down automatically (instantly, no powering off screen).

my edited autounattend.xml file:
![autounattend](https://github.com/user-attachments/asse
![win11_missing_drivers](https://github.com/user-attachments/assets/fe6e715a-b427-41eb-a46b-3f478f4e61f1)
ts/a7d79091-425f-409a-a212-2c897785097f)

**Comment by Matyanson** [comment]
Also, it is a brand new laptop so everything was functional.

**Comment by memstechtips** [comment]
What @JXRNO said here is exactly what you should do. The issues you're having is most probably because the correct drivers and Lenovo software isn't installed to properly handle all of the hardware.

**Comment by Matyanson** [comment]
Thank you for your help. I already did a clean unaltered win11 install and then I did exactly what was mentioned here. With the exception of using NVCleanstall to install nvidia drivers. The system is running fine now and the notebook is not overheating.
