### ISSUE TITLE
winget require powershell credentials when fresh install Windows

### ISSUE THREAD

**Issue by phjtieudoc** [memstechtips/UnattendedWinstall#104]
I fresh install Windows 10 June 2024 Update with Standard version of UnattendedWinstall on a VMWare, when I use CTT to install with Winget, the PowerShell menu dispalyed a popup that require "attempt installation with specific user credentials", that's weird since I fresh install with a fresh ISO, and the old version of UWinstall with the same ISO, the Winget work just fine. I don't know what to type since it always say wrong password.

![image](https://github.com/user-attachments/assets/ffd2e807-62a5-462f-b4d2-fb06f93cab90)
![image](https://github.com/user-attachments/assets/5855b065-3efa-4538-8e17-460c3976dd4d)

**Comment by memstechtips** [comment]
Hi, I think it's related to User Account Control Settings.

Please Run this in CMD or PowerShell and restart your PC then test again.

```
:: Enables User Account Control (Default Value)
reg.exe add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System" /v EnableLUA /t REG_DWORD /d 3 /f ```

**Comment by felipedamata** [comment]
@phjtieudoc You should execute the command without the ```entries, probably a copy paste mistake. So, it would be:
reg.exe add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System" /v EnableLUA /t REG_DWORD /d 3 /f

Tip: This must be run as admin
