### ISSUE TITLE
IoT-LTSC-Like - File Explorer Quick Access

### ISSUE THREAD

**Issue by HC1Gunner** [memstechtips/UnattendedWinstall#107]
Does the IoT-LTSC-Like autounattened file mess with file explorer's "quick access" on its left panel. Since my clean install with this xml file, my Quick Access has not populated one single folder.
I went to options, on the general tab did a Restore Defaults, and on the view tab, Reset Folders, this fixed nothing.
I then created a new User account, logged on, did a bunch of downloads using only two folders, and opened a couple of the same folders a bunch of times, and it never populates the Quick Access area.

Wanting to image my C-drive with everything working, quick access is import for me, as I have an app used daily that pulls info from that part of windows.

**Comment by memstechtips** [comment]
I didn't include a specific entry related to removing or disabling Quick Access no, but a lot of the tracking features have been disabled through registry entries and that could have an effect on Quick Access. I'm not too sure which entry it could be though to be honest.

**Comment by HC1Gunner** [comment]
Let me ask you this, if I...
I'm thinking about using the option to reinstall windows and keep your files and folders, without your autounattended file, do you have another app that will remove the bloat from 10 after it's been installed?

**Comment by memstechtips** [comment]
Yes, check the FAQ on the README page. It's already answered there with a link to a video tutorial.

**Comment by HC1Gunner** [comment]
TY you Sir, much appreciated!

**Comment by HC1Gunner** [comment]
(1) Did you use Chris's tool to create the autounattened file?
(2) If so, If I use the Run OO Shutup 10, and select Undo All Changes (factory settings), would that fix windows registry and allow quick access to work?

**Comment by ekungurov** [comment]
Try resetting Start_TrackDocs registry entry to 1.
