### ISSUE TITLE
No Issue

### ISSUE THREAD

**Issue by Querzion** [memstechtips/UnattendedWinstall#11]
Great Insight to create such a file & guide, this is much easier then other methods I have looked into, and I am currently changing all my Windows 10/11 ISO's to all become AutoUnattend Versions, with an "-EXTRAs" folder that holds some of the drivers that Windows isn't really great at fixing by it's self + the Swedish Dvorak Layout that I always end up installing, since Windows is to lazy to add that as a standard official choice. Linux is so much handier that way. Thank you! So nice to have a de-bloated Windows installation from the getgo.

**Comment by cryeprecision** [comment]
Maybe @memstechtips should set up the discussions page for this repo so stuff like this doesn't clutter the issues. (No offence)

**Comment by memstechtips** [comment]
@Querzion Thanks so much for your feedback and I'm glad it served as a base for you to just add whatever you needed, makes it really easy.

@cryeprecision That's a fantastic idea. I can create a discussions page like you said and I will in the future, but for now, you guys can join my Discord here https://discord.gg/Z9nUfGmm - I have a discussions channel there for this project as well.
