### ISSUE TITLE
Can't add Network printer

### ISSUE THREAD

**Issue by Deschne** [memstechtips/UnattendedWinstall#113]
Just installed a fresh Win 11 using IoT unattended, but i can't install network printers.
Any hint as to what i have to do? 

Thanks. :)

**Comment by mjsr** [comment]
I'm just passing by but this seems an incredibly low effort issue report. Additional information would be great to help others.

Have you checked if you have the Print Spooler running?

WIN+R to open the Run menu. Type services.msc and press enter. Check Print Spooler.

**Comment by ffiesta** [comment]
> Just installed a fresh Win 11 using IoT unattended, but i can't install network printers. Any hint as to what i have to do?
> 
> Thanks. :)

Hi, network printers (trough wifi or trough ethernet), IP or using windows find printers! 

You need to be more especific, by I suppose that you are trying setup a new printer using windows find printers, and this setupr remove the windows help setup new printer.

**Comment by ekungurov** [comment]
Which kind of network printer? If it is connected to another PC, it could be an issue with that PC, and you also need printer driver for W11 added on that PC (even it it uses W10). If it is a truly network printer, try running SSDPSRV service and setting it to auto.

**Comment by memstechtips** [comment]
The answer file doesn't change anything related to network printers.
I'm using a Canon network printer without any issues, just make sure you install the network printer using the correct Driver that you download from the printer manufacturer website.

**Comment by ekungurov** [comment]
@memstechtips I believe that depending on a network printer type, SSDPSRV could be required. I am not 100% sure but service description makes me to think so.
