### ISSUE TITLE
Install Windows 11 on external USB drive

### ISSUE THREAD

**Issue by nitschis** [memstechtips/UnattendedWinstall#121]
Currently, Windows 11 can not be installed on an external USB drive. Are there tweaks to remove these restrictions?

I know of a few tools which offer this option to some extent: Windows To Go Creator, Rufus, WinToUSB.

**Comment by ahmdsr** [comment]
Use another device to prepare your USB drive, and just use Rufus

**Comment by nitschis** [comment]
Then the autounattend.xml does not work.

**Comment by SheepCommander** [comment]
Did you follow this? https://www.youtube.com/watch?v=pDEZDD_gEbo&t=0s

**Comment by yewyewXD** [comment]
> Currently, Windows 11 can not be installed on an external USB drive.

Why not? Use [Create Windows 11 Installation Media](https://www.microsoft.com/software-download/windows11)

```
Make sure you have:
- An internet connection (internet service provider fees may apply).
- Sufficient data storage available on the computer, USB, or external drive you are downloading the .iso file to.
- A blank DVD disc with at least 8GB (and DVD burner) to create a bootable disc. We recommend using a *blank USB* or blank DVD, because any content on it will be deleted during installation.
```

**Comment by nitschis** [comment]
Are you guys actually reading the report? How does any of this help with installation on an external medium?

**Comment by memstechtips** [comment]
These files are not made for a "Windows to Go" installation, it's intended for a normal Windows installation. Currently there is no plan to support Windows To Go installations either, to be honest, I'm not even sure if you can use answer files on Windows To Go installations.

**Comment by nitschis** [comment]
Thous, I am asking if it is possible to remove the limitation of not being able to install on an external SSD. I have no interest in "Windows to Go". I just want a static installation on an external drive.

**Comment by OmarKSH** [comment]
@nitschis You can use DISM to apply a windows image (or a much easier tool called [DISM++](https://github.com/Chuyu-Team/Dism-Multi-language)) to any disk (external or internal) then copy the answer file you want to use to "Windows/Panther/unattended.xml" (Note that you will need to create that directory, it doesn't exists on a fresh installation)

**Comment by ahmdsr** [comment]
> Thous, I am asking if it is possible to remove the limitation of not being able to install on an external SSD. I have no interest in "Windows to Go". I just want a static installation on an external drive.

when you install windows on an external drive you call it Windows to Go my dude

**Comment by nitschis** [comment]
> > Thous, I am asking if it is possible to remove the limitation of not being able to install on an external SSD. I have no interest in "Windows to Go". I just want a static installation on an external drive.
> 
> when you install windows on an external drive you call it Windows to Go my dude

Why even take part in the conversation if you don't understand the premise of the whole topic? No, that's not what you call "Windows to Go".

@OmarKSH Interesting, the file will then be loaded at first boot? I will check it out.

**Comment by OmarKSH** [comment]
@nitschis It will be applied during the OOBE phase, you will see a CMD window appearing then disappearing multiple times.
