### ISSUE TITLE
"Microsoft Edge WebView2 Runtime" is not removed from installation

### ISSUE THREAD

**Issue by SheepCommander** [memstechtips/UnattendedWinstall#122]
Shown below in the Fourth line:

![image](https://github.com/user-attachments/assets/a10510fe-3f79-48d3-9bec-0630e554e398)

I used the Core version of the unattended file, but "Microsoft Edge WebView2 Runtime" is still installed.

What can I do to delete it now, and what line can be added to the XML to make sure it's deleted on setup?

**Comment by SheepCommander** [comment]
This is after I already tried re-running the "C:\Windows\Setup\Scripts\remove edge.bat" script

**Comment by ekungurov** [comment]
You shouldn't remove it without finding a proper replacement

**Comment by SheepCommander** [comment]
Okay thanks!
