### ISSUE TITLE
BSOD trying to install Windows 10

### ISSUE THREAD

**Issue by Exohrecho** [memstechtips/UnattendedWinstall#125]
So, as of right now that pc had some _technical_ problems leading to it being unusable. But I'm getting a laptop tomorrow with no OS.

My problem is that, when booting from the bootable usb (didn't matter what method I used) it would work right before when the setup starts where it would BSOD with the stop code SERVICE_EXCEPTION. I tried to install it like 5 times and every single time I got the same stop code BSOD. 

For more context, before attempting installation by 2-3 days I used WinUtils and ran the tweaks and OO Shutup also from WinUtils. Didn't install anything, just ran the recommended tweaks (and enabled ultimate power thing) and the same for OO, enabling only the recommended settings.

My friend, who made 2 bootables to install an OS on my soon to get laptop (Windows 10 + Standard Unattended and Linux Mint, in case the win10 install is broken) has tried to run the bootable on a Virtual Machine. For the first time he did it, it wouldn't let him create the VM getting an error saying "Insufficient permission to access file.". 

For the second attempt, he said the problem was fixed by "bringing out the hammer", as a joke of course, but didn't explain what he did exactly. This time it worked, but during setup his VM **AND** actual PC BSOD. He says it's probably some issue with VMWare and not the USB. 
Pictures of the error and BSOD he got will be attached.

Tying in with his first attempt, from what I've read the SYSTEM_SERVICE_EXCEPTION is either caused by a driver or it's something something about a "privileged process" trying to access and use a "non-privileged process". 

From what I've seen online I'm the only one that had this problem, nobody else had the exact same issue and those that are remotely different are way to different to my problem. Any help?
![Screenshot_13](https://github.com/user-attachments/assets/f0ea07dd-15bb-4cb1-b8aa-d2ae8bb50ade)
![IMG_20240829_175154](https://github.com/user-attachments/assets/1d631540-f85c-4c01-9b43-df8ded7d2d0c)

**Comment by ekungurov** [comment]
Probably VMWare issue or actual hardware issue. Not related to the project

**Comment by Exohrecho** [comment]
Sure, I'll tell him that, but what about the first part where it didn't work at all on my PC?

**Comment by ekungurov** [comment]
Do you think the Autoattend file is the source of troubles? Why? Was your laptop working before that? 
Try a regular install without autoattend.xml

**Comment by memstechtips** [comment]
I doubt that this issue is related to the UnattendedWinstall project.
