### ISSUE TITLE
Let Windows PE to autodetect Windows edition and product key from the UEFI tables

### ISSUE THREAD

**Issue by bfg01** [memstechtips/UnattendedWinstall#128]
I read that xmls from here and Schneegans generator all require forcibly specifying a Windows edition and product key, even if not used for immediate activation.

But Windows PE's (the Windows installer) default behavior is autodetecting them by reading the tables embedded in the UEFI.

What can I do in the xml to achieve this default behavior?

Thanks.

**Comment by memstechtips** [comment]
I have added entries that creates an `ei.cfg` file during that part of the windows setup, but it gets ignored by the Windows setup on the latest builds/ISO's of Windows. This is unrelated to the `autounattend.xml` answer file, it's an issue in the latest Windows builds.

A workaround is to click on the back button in the upper left corner when you get to the edition selection screen. The next time you see that screen it will display all available options.

**Comment by kendi182** [comment]
Here is a solution to the problem regarding showing the Windows version menu for both 10 and 11.
there is no need to use the ei.cfg file

[https://github.com/cschneegans/unattend-generator/issues/170#issuecomment-2676387896](url)

@memstechtips @bfg01
