### ISSUE TITLE
Please add the no sleep, and laptop lid settings

### ISSUE THREAD

**Issue by MrCrowley33** [memstechtips/UnattendedWinstall#132]
I've been trying to transplant the settings i have from the schneegans xml i made that makes the computer not go to sleep and keeps the monitor on, and changes the lid settings to do nothing.

I can't for the life of me get this to not error out when i try to add it to your standard install.

just a simple powercfg script to get added.

<File path="C:\Windows\Setup\Scripts\timeoutcfg.cmd">
Powercfg /Change monitor-timeout-ac 60
Powercfg /Change monitor-timeout-dc 0
Powercfg /Change standby-timeout-ac 0
Powercfg /Change standby-timeout-dc 0
</File>

**Comment by memstechtips** [comment]
Have you been able to fix this issue?

In v2.0.0 linked below, I have reworked the Power Settings part of the file https://github.com/memstechtips/UnattendedWinstall/releases/tag/v2.0.0

Feel free to reopen the issue if it's not fixed.
