### ISSUE TITLE
Standard gives errors when trying to install any program from CTT WinUtil

### ISSUE THREAD

**Issue by limbo666** [memstechtips/UnattendedWinstall#133]
It seems that something is wrong on the dependenies for **_msstore_** on Win11_23H2_EnglishInternational_x64v2
The CTT Win Utility gives the following error  `Failed when searching source: msstore` which seems to be this: https://github.com/microsoft/winget-cli/issues/3596

Since there is no browser installed on this configuration the browser installation bit tricky.

**Comment by memstechtips** [comment]
If you ran the Windows Utility, it should have also installed Chocolatey by default.
Open a new PowerShell window as Admin and run:
`choco install firefox`

If Chocolatey is not installed, install it manually. https://chocolatey.org/install

**Comment by limbo666** [comment]
Yes Choco is missing.
Isnatlling manually enables user to `choco install` packages. Thank you.

CTT still cannot perform any insatllation after that. It still complains about msstore.
Any ideas?
![image](https://github.com/user-attachments/assets/4c841ad3-4460-4cb3-9c29-8be429c640ae)

**Comment by limbo666** [comment]
For sure this is a winget releated issue. 
Closing as not caused solely by UnattendedWinstall

**Comment by Carbon-Axion** [comment]
you need to change your region back to usa or whereever you live
