### ISSUE TITLE
issues with notfications

### ISSUE THREAD

**Issue by hdgetban** [memstechtips/UnattendedWinstall#14]
so when i click this 
![image](https://github.com/memstechtips/UnattendedWinstall/assets/156936988/40d931ed-abdc-41b4-a580-daf359335ec0)
it doesnt show up and i need it for discord so how do i enable it?

**Comment by memstechtips** [comment]
Open CMD or Powershell as Admin and run the following commands:

```
reg.exe add "HKEY_CURRENT_USER\SOFTWARE\Policies\Microsoft\Windows\Explorer" /v DisableNotificationCenter /t REG_DWORD /d 0 /f
reg.exe add "HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\PushNotifications" /v ToastEnabled /t REG_DWORD /d 1 /f
```
Hopefully it works.

**Comment by hdgetban** [comment]
it works thanks

**Comment by hdgetban** [comment]
it works but i dont get notfications so how do i disable it again

**Comment by hdgetban** [comment]
WAIT ACTUALLY NO I DONT WANNA DISABLE IT BECAUSE I NEED THE CALENDER
