### ISSUE TITLE
Disabling "Let websites provide locally relevant content" is not working

### ISSUE THREAD

**Issue by bfg01** [memstechtips/UnattendedWinstall#143]
The corresponding key and value are:
"HKEY_CURRENT_USER\Control Panel\International\User Profile" /v "HttpAcceptLanguageOptOut"
which are featured in the Standard xml in this repo.

But when using the xml to auto-install Windows and later checking Settings > Privacy > General, I see "Let websites provide locally relevant content" is actually enabled and not disabled. I need to manually disable it. All other registry settings as far as I remember were respected, though.
Also, by manually browsing the registry, I noticed the key and value were not there at all, as if never created (or erased...)

Tried with the Standard xml from here, and also with a version generated by Schneegans service and modifying it, which uses the approximation of first loading the NTUSER.DAT and then using "HKU\DefaultUser" instead of "HKEY_CURRENT_USER".
Same results.

Tried both in Windows 10 and 11.

Could you check it?
Thanks.

**Comment by yeah-Buddyy** [comment]
Unfortunately, there are some registry keys that are deleted after every system restart and this is one of them. To fix this, you need to create a task that adds this registry key after each system restart. Of course, you can also use HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Run

**Comment by memstechtips** [comment]
Interesting find and thanks for the feedback @yeah-Buddyy
