### ISSUE TITLE
Error finding unattended answer file

### ISSUE THREAD

**Issue by Tyology** [memstechtips/UnattendedWinstall#15]
Followed the directions to add the xml file to the iso. This is the error I get after seeing the initial install screen and clicking on Insall Now and it shows text "Setup is starting", it then displays this:

"Windows setup encountered an internal error while searching for answer file."

**Comment by Theridgeback** [comment]
I had the same problem,
If you click on the unattended.xml file it downloads a html page with the xml flie on it.
Click on the link and open the xml in another tab, 
there you will find the xml file,

click on copy raw file and then save this to the unattended.xml file

**Comment by memstechtips** [comment]
Yes, alternatively you can open the file on GitHub, click on the "Raw" button, then on the next page, right click and save as, it will then download as .xml.

**Comment by memstechtips** [comment]
Closing.
