### ISSUE TITLE
How to Run the Script on an "Existing System"....?

### ISSUE THREAD

**Issue by leeuniverse** [memstechtips/UnattendedWinstall#152]
So, would like to clean up a Win11 system I have that's already been installed.
How to?

p.s. Yes, I know you stated to "Use Christ Titus" but Chris Titus' doesn't do everything yours does from what I understand per your Info, plus I've added and changed stuff, some of which Titus also won't do.

Thanks

**Comment by memstechtips** [comment]
Hey there,

This should be fixed in v2.0.0 - https://github.com/memstechtips/UnattendedWinstall/releases/tag/v2.0.0

Feel free to reopen the issue if it's not fixed.
