### ISSUE TITLE
calendar doesn't pop up

### ISSUE THREAD

**Issue by eyewee** [memstechtips/UnattendedWinstall#153]
Right after fresh install, when you hover over date and hour, a calendar should pop up but it doesn't. Tried to install mail and calendar from the store, cliqued on repair, reset, nothing helps. (btw the app is 213 mb for some reason)

**Comment by serajr** [comment]
Re-enable Notification Center, try this:

- Press the Windows key + R then type in:
regedit (then hit ok)
- Navigate the file path:
Computer\HKEY_CURRENT_USER\Software\Policies\Microsoft\Windows\Explorer
- Double-click on DisableNotificationCenter > change the value data to 0

**Comment by McJordan2000** [comment]
Like Serajr said calander and notification are disabled during the running of the script, i personally would look through the script and see what you want to keep and what u want to get rid off and it minght disable/remove somthing you really want to keep.

**Comment by PantiesIsStoopid** [comment]
The simple solution is to open Chris Titus windows utility,go to the tweaks tab, check disable taskbar calendar and finally click undo selected tweaks. 

If you are unsure on how to open the app paste this into a power shell window run as administrator:

```

iwr -useb https://christitus.com/win | iex

```

**Comment by memstechtips** [comment]
What @PantiesIsStoopid suggested will work just fine.
This will also work https://github.com/memstechtips/UnattendedWinstall/blob/main/TROUBLESHOOTING.md#calendar-and-notifications-whatsapp-not-working
