### ISSUE TITLE
Ultimate Performance Power Plan BUG

### ISSUE THREAD

**Issue by adriansaav27** [memstechtips/UnattendedWinstall#158]
The power plan is not activated at maximum performance. To solve this problem, you must replace the lines:

_powercfg -duplicatescheme e9a42b02-d5df-448d-aa00-03f14749eb61
powercfg -setactive e9a42b02-d5df-448d-aa00-03f14749eb61_

by:

_$maxPerformanceScheme = powercfg -duplicatescheme e9a42b02-d5df-448d-aa00-03f14749eb61
$guid = [regex]::Match($maxPerformanceScheme, '[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}').Value
powercfg -setactive $guid_

**Comment by memstechtips** [comment]
Hey there,

This should be fixed in v2.0.0 - https://github.com/memstechtips/UnattendedWinstall/releases/tag/v2.0.0

Feel free to reopen the issue if it's not fixed.
