### ISSUE TITLE
Can't select Pro version because the system came with Home installed

### ISSUE THREAD

**Issue by SrGeneroso** [memstechtips/UnattendedWinstall#16]
I found this problem earlier, is not that the script doesn't work, but that w11 (and possibly 10) can detect the OEM preinstalled OS, I don't know how and I would like to learn why as only saves a single step.
I'm referring to the step where you choose if you want the Pro version, the Home, then N... and so on. In practice, it means that if you bought a system that was preinstalled with let's say the Home edition it will only show you that option.

A workaround to enable the selection panel during installation is that you have to include a "ei.cfg" file with 
`[Channel]
Retail`
in the folder sources.
Is there a way to do it from the script? I'm going to do it manually but it would be great to include it.

I leave this here in case helps somebody else

**Comment by SrGeneroso** [comment]
btw, this is the source where I learnt about it
https://www.kapilarya.com/fix-cant-select-windows-10-edition-during-clean-installation

**Comment by memstechtips** [comment]
I'm not sure if it can be done in the file, but I will have a look at it sometime.

**Comment by memstechtips** [comment]
@SrGeneroso Could you please edit your answer file and replace the userdata section (in the WindowsPE phase) with the following and report back?
```
<UserData>
        <AcceptEula>true</AcceptEula>
        <ProductKey>
	<Key>00000-00000-00000-00000-00000</Key>
        <WillShowUI>Always</WillShowUI> <!-- This ensures the UI will show to select the edition of Windows -->
	</ProductKey>
</UserData>
```

**Comment by memstechtips** [comment]
I've added the following command to the answer file and I'm closing the issue.
```
<WillShowUI>Always</WillShowUI> <!-- This ensures the UI will show to select the edition of Windows -->
```

**Comment by MicaelJarniac** [comment]
I just downloaded the answer file, and mine also only showed the Home edition. I installed it with Ventoy.

**Comment by memstechtips** [comment]
To fix this issue https://github.com/memstechtips/UnattendedWinstall/issues/74#issuecomment-2249619805

**Comment by kendi182** [comment]
Here is a solution to the problem regarding showing the Windows version menu for both 10 and 11.
there is no need to use the ei.cfg file

[https://github.com/cschneegans/unattend-generator/issues/170#issuecomment-2676387896](url)
