### ISSUE TITLE
Preparing Automatic Repair

### ISSUE THREAD

**Issue by JoshCobra** [memstechtips/UnattendedWinstall#160]
**For Windows 11 24H2** 
Using [Standard](https://github.com/memstechtips/UnattendedWinstall/blob/main/Standard/autounattend.xml) Version

After you choose the Disk for your installation it might reboot and appear on your screen, "Preparing Automatic Repair".
1. Choose, Select another operating system, and choose the: volume1 or volume2, **the closest one**, this worked for me

Also, I have 3 disks installed on my machine, two nvme and one HDD, ryzen7 5800x, rtx3060

**Comment by memstechtips** [comment]
Hey there,

This should be fixed in v2.0.0 - https://github.com/memstechtips/UnattendedWinstall/releases/tag/v2.0.0

Feel free to reopen the issue if it's not fixed.
