### ISSUE TITLE
Can't run script even after running "Set-ExecutionPolicy RemoteSigned"

### ISSUE THREAD

**Issue by trparky** [memstechtips/UnattendedWinstall#164]
This is my current setup...
```
Get-ExecutionPolicy -List

        Scope ExecutionPolicy
        ----- ---------------
MachinePolicy       Undefined
   UserPolicy       Undefined
      Process       Undefined
  CurrentUser    RemoteSigned
 LocalMachine    RemoteSigned
```

I executed `Set-ExecutionPolicy RemoteSigned` as per the suggestion yet nothing changes in the `Get-ExecutionPolicy -List` output. I still receive the following error...
`.\UWScript.ps1: File C:\Users\user\Downloads\UnattendedWinstall-2.0.0\UWScript.ps1 cannot be loaded. The file C:\Users\trpar\Downloads\UnattendedWinstall-2.0.0\UWScript.ps1 is not digitally signed. You cannot run this script on the current system. For more information about running scripts and setting execution policy, see about_Execution_Policies at https://go.microsoft.com/fwlink/?LinkID=135170.`

**Comment by drakin003** [comment]
set it to unrestricted then try :)

**Comment by memstechtips** [comment]
@trparky Run `Set-ExecutionPolicy Unrestricted` in PowerShell and then try run the `UWScript.ps1` file again.
You can also right click the file and select "Run with PowerShell."
