### ISSUE TITLE
Potential cdkey leak

### ISSUE THREAD

**Issue by Brzhk** [memstechtips/UnattendedWinstall#165]
I'm just checking with you @memstechtips, this is not a real cdkey, is it?

_Originally posted by @Brzhk in https://github.com/memstechtips/UnattendedWinstall/pull/162#discussion_r1827038917_

**Comment by memstechtips** [comment]
Yo, I answered your question here:
https://github.com/memstechtips/UnattendedWinstall/pull/162#discussion_r1830915756
