### ISSUE TITLE
XML is not well-formed

### ISSUE THREAD

**Issue by cschneegans** [memstechtips/UnattendedWinstall#18]
I am somewhat surprised that this `autounattend.xml` works since it is not well-formed XML. GitHub even [highlights](https://github.com/memstechtips/UnattendedWinstall/blob/main/autounattend.xml) several well-formedness violations, namely unescaped `&` characters.

**Comment by memstechtips** [comment]
It might not be well formed but it works 😅

**Comment by memstechtips** [comment]
@cschneegans I didn't even notice it was you when looking at this issue. 
Firstly, thanks for your https://github.com/cschneegans/unattend-generator it's an awesome project.

Would you be available or open to talk privately on Discord sometime?
