### ISSUE TITLE
Windows update add Copilot

### ISSUE THREAD

**Issue by allentd** [memstechtips/UnattendedWinstall#184]
---

- Windows 10 Version 22H2 (OS Build 19045.5131)
- UnattendedWinstall v1.0.0 Standard

---

Hello, thank you for the script.

I was using Standard version of the UnattendedWinstall script around 3 months ago to install Windows 10, not the latest unified one. Windows updated today and added Copilot.

It's not listed in the Programs list, anyone know how can we remove it? Searching the internet only show how to disable, not removed completely.

Thanks!

Screenshot.
![Screenshot (29)](https://github.com/user-attachments/assets/175717f0-32cf-4ef4-b022-cc1fa4b99bd4)

**Comment by Tmp341** [comment]
Which one is Copilot?

**Comment by allentd** [comment]
> Which one is Copilot?
> 
> Also:
> 
> > To remove the LCU after installing the combined SSU and LCU package, use the [DISM /Remove-Package](https://docs.microsoft.com/windows-hardware/manufacture/desktop/dism-operating-system-package-servicing-command-line-options) command line option with the LCU package name as the argument. You can find the package name by using this command: DISM /online /get-packages.

Thanks! I'll try that.

Most like the top or 3rd from the top updates that added the Copilot.

**Comment by allentd** [comment]
Thanks! I'll try that.

Most like the top or 3rd from the top updates that added the Copilot.
