### ISSUE TITLE
Inconsistency Between Title and Value - ClearPageFileAtShutdown

### ISSUE THREAD

**Issue by GokhanTurk** [memstechtips/UnattendedWinstall#2]
Hello,

I have noticed a line in the autounattend.xml file that appears as follows:

```
:: Clears Memory Page File at Shutdown
reg.exe add "HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management" /v ClearPageFileAtShutdown /t REG_DWORD /d 0 /f
```

You are stating that it clears the memory page file at shutdown, but the value is set to 0. Is this the correct way to achieve this? I am a bit confused.
Thank you for your assistance.

**Comment by memstechtips** [comment]
Thanks for pointing that out, the value is indeed correct but the description is not, I've changed it to the following:

```
:: Controls whether the memory page file is cleared at shutdown. Value 0 means it will not be cleared, speeding up shutdown. 
reg.exe add "HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management" /v ClearPageFileAtShutdown /t REG_DWORD /d 0 /f
```
