### ISSUE TITLE
Insecure UAC settings which starts everything as administrator

### ISSUE THREAD

**Issue by Syntax3rror404** [memstechtips/UnattendedWinstall#20]
How to fix this issue inside the answer file? 

![image](https://github.com/memstechtips/UnattendedWinstall/assets/57288415/50e2a2bb-85a1-4e01-ad89-1af5ea764541)

**Comment by LeoTheLegion** [comment]
@Syntax3rror404 I think what you are looking for is on line 243 or find the comment "Disables User Account Control"

![image](https://github.com/memstechtips/UnattendedWinstall/assets/39383985/7d4444e4-eae8-4db8-a868-2b1eb79d69c5)

**Comment by memstechtips** [comment]
Remove all of these entries:
```
:: Disables User Account Control
reg.exe add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System" /v EnableLUA /t REG_DWORD /d 0 /f

:: Disables User Account Control
reg.exe add "HKU\DefaultUser\SOFTWARE\Microsoft\Windows\CurrentVersion\Privacy" /v UserAccountControlSettings /t REG_DWORD /d 0 /f

:: Disables User Account Control
reg.exe add "HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Privacy" /v UserAccountControlSettings /t REG_DWORD /d 0 /f
```
