### ISSUE TITLE
An interesting catch

### ISSUE THREAD

**Issue by aka-0x4C3DD** [memstechtips/UnattendedWinstall#24]
while I was looking through this .xml in vs code, idk why I thought of giving Edge a try, and it shows 

![image](https://github.com/memstechtips/UnattendedWinstall/assets/93938476/45511620-4f06-41ba-9780-d48e6c0835e2)

but I believe it should show something similar to this

![image](https://github.com/memstechtips/UnattendedWinstall/assets/93938476/a0afb36c-5dcc-448b-80a0-07e9b7769c89)

I might be wrong, but is this an issue?

**Comment by Syntax3rror404** [comment]
This is because the xml is not right formated. Some `&` needs to be escaped. 

You can see this if you open the file inside github then the wrong formated partes are marked red.

**Comment by memstechtips** [comment]
I have just updated the file, please see if the issue still persists and get back to me.

**Comment by Syntax3rror404** [comment]
Yep, now the xml is valid
