### ISSUE TITLE
[Sugguestion] Please add version that still have microsoft account support

### ISSUE THREAD

**Issue by chokchai** [memstechtips/UnattendedWinstall#25]
Because one drive and BitLocker will be broken.
completed remove support Microsoft account is affecting the usage of its.

Thank you.

**Comment by Syntax3rror404** [comment]
Onedrive is not broken, its basically removed.

If you want to use onedrive, you can exclude the parts which disables onedrive in the xml.

Search for "onedrive" in the xml and remove all the lines and you're done.

**Comment by memstechtips** [comment]
I did not remove Microsoft Accounts, they are just bypassed/disabled during the setup process. You can go through the setup process and create an Offline/Local account with your name. Once you're signed in, just go to Accounts and click on Sign In, your local account will be converted to a Microsoft Account.
![MS Acc](https://github.com/memstechtips/UnattendedWinstall/assets/172593213/0ba12a2f-db7e-472e-92c5-7bb7dcb7c2e7)

As for OneDrive @Syntax3rror404 is correct, that is one way of doing it.

But you can also just download and install it [from Microsoft](https://www.microsoft.com/en-za/microsoft-365/onedrive/download), it still works.
![OneDrive](https://github.com/memstechtips/UnattendedWinstall/assets/172593213/50e16b14-c957-4a76-9396-8ec982b2cd33)

BUT, before it will launch and sync your files, you will need to edit the following registry key:
```
HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Windows\OneDrive
```
Double Click the “DisableFileSyncNGSC” and change the value to 0.

![OneDrive Reg](https://github.com/memstechtips/UnattendedWinstall/assets/172593213/7d6c166d-eb35-4390-8487-13790f887f76)

I trust that this will resolve the issue and I'm closing it with this comment.
