### ISSUE TITLE
Just a general suggestion

### ISSUE THREAD

**Issue by zachjtmurphy** [memstechtips/UnattendedWinstall#26]
I don't mean any disrespect or to cause issues. I just found your project a few hours ago and I have a few suggestions.

I have noticed you make many individual changes every few minutes to large portions of this project. In my experience with the past few hours, I have constantly had to re-flash the "auto unattend.xml" file every 15 - 20 minutes. With all of the changes, every few minutes new users continuously have to re-download the files they need which causes issues for the end user.

**My suggestion:**
1. Use a development branch where you make any changes and then release versions such as v0.0.1 - v1.0.0 to the main branch or even use the releases tab feature of GitHub. Using a development branch and only pushing new code to the main branch with every new major release allows for an non-stressful and clean project, especially for the end user.

2. I noticed you like to create and push many commits back to back separately with minor changes between each. With git, there is the ability to push multiple commits in one push. I would highly suggest doing that. It creates less chaos and havoc for the end-user and a cleaner commit history which makes looking for changes that you might have to rollback easier to find. I have noticed that you are using a changelog but in the end that still does not help in regards to the roughly 5 commits you push within a 3 - 7 minute time span.

**Comment by zachjtmurphy** [comment]
![image](https://github.com/memstechtips/UnattendedWinstall/assets/173928308/4b078e60-2090-42ab-bedd-d2f7cd83064e)

There are many commits here that easily could of been pushed in one simple change rather than 7 different changes.

**Comment by memstechtips** [comment]
Thanks so much for your feedback and suggestions! 

As you can tell, I don't have any experience with GitHub, I didn't even know markdown files exist before starting this project lol.
Tonight was chaotic because I changed a lot of things and went back and forth and I apologize for making it frustrating for you and the other end users here.

I will definitely have a look at those things you mentioned to make it cleaner.

I REALLY appreciate your help, thanks.

**Comment by zachjtmurphy** [comment]
You're welcome, happy to help.

**Comment by memstechtips** [comment]
Thanks to your suggestion I have learned a lot in the past few days with regards to Git and to manage this repo more efficiently, so thanks for that. I will be creating a development branch and test things out first and then commit into the main branch from time to time. Thanks again.
