### ISSUE TITLE
Start menu search index issue

### ISSUE THREAD

**Issue by kixico** [memstechtips/UnattendedWinstall#27]
Best match results and/or any related app results purged from start menu search index after installation. Attempted to make sure areas of index weren't excluded, rebuilt index, tweaked separat installs with and without the start menu registry edits in the xml yet no ability to simply windows start menu search for non windows default apps ex. firefox, discord, etc. Any insight would be great

**Comment by Shia0410** [comment]
Try running 'WinKey + R' and type in `ctfmon.exe`. Had this error back in windows 7. Let me know if that works. If it does, perhaps just write a short silent .bat script that you just add during startup, or add it into the .xml file for the installation so that it does it automatically.

**Comment by yuri0r** [comment]
facing the same issue, ctfmon.exe didnt help.
