### ISSUE TITLE
Some issues with Proxmox.  [ autounattended.xml ] file.

### ISSUE THREAD

**Issue by mithubindia** [memstechtips/UnattendedWinstall#29]
I tried to create  a very small iso on Linux using this command.

mkisofs -o  -R unattendedwin.iso   /home/user/autounattend.xml

Whenever I use unattendedwin.iso as additional cddrive in Proxmox,  windows sees autounattended.xml file in truncated format and refuses to use it [ obviously ]  .

Do you know any other method of creating a separate iso for autounattended.xml  [  This saves playing with original windows iso and problems related to put the autounattended.xml file in a same iso ]  This will be super useful for Virtual machine on all platforms like Proxmox, Hyper-V , Vmware, Neutanix etc.

**Comment by memstechtips** [comment]
Hi there.

I don't know of a method at this time. Will get back to you if I do though.
In the meantime, if you figure it out, please share the soluiton here.

**Comment by Syntax3rror404** [comment]
Use [packer ](https://www.packer.io/)to create your proxmox windows template with the autounattend.xml and then just clone a vm from the template
