### ISSUE TITLE
Trey Icons not Working 

### ISSUE THREAD

**Issue by TahoeMiah** [memstechtips/UnattendedWinstall#31]
Love this script. My only issue is that the trey icons are not working in 11 Pro. I don't get anything when I left click on wifi, sound or battery only right click

**Comment by skhaz** [comment]
> Love this script. My only issue is that the trey icons are not working in 11 Pro. I don't get anything when I left click on wifi, sound or battery only right click

It is working for me (installed two days ago)

**Comment by TahoeMiah** [comment]
Going to try on different hardware. First was a Dell XPS 16. Installing now on a Lenovo P14S

**Comment by anouk** [comment]
Downloded a new ISO and things are working better now

**Comment by memstechtips** [comment]
@TahoeMiah Glad you like it! Yeah I haven't had that issue, I'm glad the new ISO fixed it for you.

**Comment by anouk** [comment]
Just to recap. I created an ISO from the DVD in a windows 11 PRO OEM disk. Then I used NTLite to add updates, inject the necessary NVME intel drivers and remove other editions of 11. Then, I added the autounattend file with anyburn.  After install, the trey icons did not work 

Same process, except I downloaded a new ISO from microsoft. No trey icon problems
