### ISSUE TITLE
MSEdge still installed

### ISSUE THREAD

**Issue by SCHEFFRA** [memstechtips/UnattendedWinstall#32]
I'm using standard autounattend.xml file. After finishing Windows installation (Win10 22H2 x64), MSEdge is still installed and I see a shortcut on the desktop. It seems that the script edgeremoval.bat is executed while installation process because there is a log file. But this log file is empty. When I start the script manually after login with admin permissions, it seems to work... MSEdge is uninstalled (except deleting the desktop shortcut). First I thought it might depend on the Windows image I use (it is the german original ISO) but I come along with the same issue using the english ISO image.

Any idea?

**Comment by ViwuAndYouKnow** [comment]
it happened to me too but only because i modified the file which caused it to crash and not work, so if you did any changes, i recommend going through it again.

**Comment by SCHEFFRA** [comment]
I also modified the script but it does not crash. I tested also the original file from GitHub and still the same result.
But I found another interesting point...in the past I was testing on a VMWare Workstation virtual machine and MSEdge was not uninstalled. My current test on a physical machine (old Dell M6600) was successfull. MSEdge is no more available.

**Comment by memstechtips** [comment]
I just updated the answer files in https://github.com/memstechtips/UnattendedWinstall/commit/a9348a19ad425bb840c2a3e4e67501a81715ef66

Edge is uninstalled on both Windows 11 and Windows 10. However, it seems to be installed on Windows 10 only when going through the Windows installation process with an internet connection. In any event, if it reappears, go to `C:\Windows\Setup\Scripts\edgeremoval.bat` and just run it as Administrator.

It will uninstall Edge but you manually have to delete the Desktop Shortcut and Start Menu Entry.
