### ISSUE TITLE
Hibernation disabled yet hiberfil.sys file still present

### ISSUE THREAD

**Issue by jhellard** [memstechtips/UnattendedWinstall#33]
I just installed the 'IoT-LTSC-Like' version and it's noted that hibernation is disabled by default which is true, however the hiberfil.sys is still present on the system. Is this intended? I've since deleted it using 'powercfg.exe /hibernate off' with no issue.

**Comment by memstechtips** [comment]
Hi there, yes I never intended for the file to be deleted. I just wanted the default state to be disabled by adding these entries.
```
:: Disables Hibernation
reg.exe add "HKLM\System\CurrentControlSet\Control\Session Manager\Power" /v HibernateEnabled /t REG_DWORD /d 0 /f
reg.exe add "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\FlyoutMenuSettings" /v ShowHibernateOption /t REG_DWORD /d 0 /f
```
