### ISSUE TITLE
[Feature Request] Disable Windows wallpaper JPEG compression

### ISSUE THREAD

**Issue by nickelberg** [memstechtips/UnattendedWinstall#34]
Windows compresses wallpapers, and in some specific cases compression will cause artifacts.
(barely visible, but still)

Here a solution, could you integrate this registry fix to your answer file?
[Is it possible to get Windows to not compress wallpapers? - Reddit](https://www.reddit.com/r/Windows10/comments/m8fopi/comment/grh146k/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button)

**Comment by memstechtips** [comment]
Thanks, I will look at adding this.

**Comment by memstechtips** [comment]
Added in [commit 288ee49](https://github.com/memstechtips/UnattendedWinstall/commit/288ee49128c99dde3e833ee733e78d56c46b78a4)
