### ISSUE TITLE
Desktop PowerShell Script do not work due to incorrect structure, link address and call method

### ISSUE THREAD

**Issue by Basmart** [memstechtips/UnattendedWinstall#35]
I'd like to propose change on line 424 from:
`# Creates Desktop Shortcut for the Chris Titus Windows Utility So You Can Easily Launch it to Install Programs
$path = "C:\Users\Default\Desktop\LAUNCH-CTT-WINUTIL.ps1"
$content = 'irm https://www.christitus.com/win | iex'
New-Item -Path $path -ItemType File -Force
$content | Out-File -FilePath $path -Encoding UTF8 -Force
`
To be replaced with:
`# Creates ps1 File for the Chris Titus Windows Utility So You Can Easily Launch it to Install Programs
$path = "C:\tmp\LAUNCH-CTT-WINUTIL.ps1"
$content = 'iwr -useb https://christitus.com/win | iex'
New-Item -ItemType Directory -Force -Path C:\tmp
New-Item -Path $path -ItemType File -Force
$content | Out-File -FilePath $path -Encoding ASCII -Force

# Create CMD file on Desktop to launch Chris Titus Windows Utility So You Can Easily Launch it to Install Programs 
$path = "C:\Users\Default\Desktop\RUN-CCT-WINUTIL-Run As Administrator.CMD"
$content = 'PowerShell.exe -ExecutionPolicy Bypass -File C:\tmp\LAUNCH-CTT-WINUTIL.ps1'
New-Item -Path $path -ItemType File -Force
$content | Out-File -FilePath $path -Encoding ASCII -Force`

**Comment by memstechtips** [comment]
Hi there and thanks so much for this, I appreciate it.
I did however just fix this using another method and pulled it through in https://github.com/memstechtips/UnattendedWinstall/commit/a9348a19ad425bb840c2a3e4e67501a81715ef66
