### ISSUE TITLE
Default language

### ISSUE THREAD

**Issue by mstup** [memstechtips/UnattendedWinstall#39]
For example, when I have Spanish language distro of Win11, how to change language during an installation and change for final users?

**Comment by ViwuAndYouKnow** [comment]
The language of the ISO is usually set when you download it from microsoft since it will ask you. To change after install you just go to language settings and change there.

**Comment by mstup** [comment]
@ViwuAndYouKnow Yes, that's clear. I just expected that there is the way to download language package specified by language code and start installation with this language. Without any additional manual steps to change the language manually after installation was completed.

**Comment by ViwuAndYouKnow** [comment]
Iguess u could try or something like this although i think this only would apply to the installer and not the actual OS.

<component name="Microsoft-Windows-International-Core" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">
<InputLocale>0409:00000409</InputLocale>
<SystemLocale>en-US</SystemLocale>
<UILanguage>en-US</UILanguage>
<UserLocale>en-US</UserLocale>
</component>

Another way is doing it manual like you said, going to language>Administrative language settings>Copy Settings iguess.

**Comment by mstup** [comment]
Thanks, will try it.

**Comment by memstechtips** [comment]
Yes you can set a default language as described by @ViwuAndYouKnow 
I suggest using the unattend generator to see how it's done there https://schneegans.de/windows/unattend-generator/
