### ISSUE TITLE
[Feature Request] autounattend to upgrade from Win10 to Win11

### ISSUE THREAD

**Issue by CladZo91** [memstechtips/UnattendedWinstall#48]
With Microsoft dropping support for Win10 would be great if a version of the xml could be made to upgrade to Win11, cleaning up the OS while keeping most of the old OS data.

**Comment by memstechtips** [comment]
I have some people testing this and working on it.
If you want you can follow this thread - https://discord.com/channels/1192038830245679177/1256006844300660800/threads/1260584790340407436

**Comment by alvesluc** [comment]
Hey! I can't see the thread because I'm not on the server, can you provide the link to it?

**Comment by memstechtips** [comment]
Sorry about that.

https://www.discord.gg/zWGANV8QAX

**Comment by Subhashis2007** [comment]
> With Microsoft dropping support for Win10 would be great if a version of the xml could be made to upgrade to Win11, cleaning up the OS while keeping most of the old OS data.

ps: if u really need win10, just use iot ltsc, 2032 is support expiration date

**Comment by memstechtips** [comment]
After some more consideration and research on this topic, I'm closing this issue.

Answer files are to be used on fresh Windows installs and won't work the same way during an upgrade. To get the same effect on an already existing Windows installation, you will have to manually "debloat" or "tweak" Windows. 

I created a video on the Chris Titus Windows Utility which might be useful for someone coming across this issue again. https://youtu.be/pldFPTnOCGM
