### ISSUE TITLE
The xml file has some issues with productkey

### ISSUE THREAD

**Issue by bayssemir** [memstechtips/UnattendedWinstall#5]
![IMG_20240624_084849.jpg](https://github.com/memstechtips/UnattendedWinstall/assets/104230074/fd77b9ef-c1ec-4c29-901d-4c8c21656add)

**Comment by memstechtips** [comment]
1. Did you change anything in the answer file or change the file name of the answer file?
2. On which Windows ISO are you using it?
3. How did you create installation media? (Rufus, Ventoy) or are you installing on a VM?

**Comment by bayssemir** [comment]
i  used ventoy and  i have also not changed the answer.xml and my last step was using anyburn to edit image

**Comment by memstechtips** [comment]
Can you test it out with a flash drive as described in Method 1? Using Rufus and then copying the answer file onto it?

**Comment by bayssemir** [comment]
> Can you test it out with a flash drive as described in Method 1? Using Rufus and then copying the answer file onto it?

let me try with method 1

**Comment by memstechtips** [comment]
@bayssemir any feedback?

**Comment by lukaszjakubiak** [comment]
I can confirm it persists after today's update.
I used windows download tool to download windows 10 ISO, then modify ISO with anyburn and put answers file onto it. After that I run image on virtual machine, both Virtual box and VMware have the same problem.

**Comment by memstechtips** [comment]
Please join my [Discord](https://discord.gg/Z9nUfGmm) so we can figure out what's going on.

**Comment by bayssemir** [comment]
> @bayssemir any feedback? 

thanks for guiding, and it was successfully installed with a clean install, and i have also watched your new instruction guidance video about the new release, thank you so much, i really appreciate you.
Big  Fan

**Comment by bayssemir** [comment]
> I can confirm it persists after today's update.
> I used windows download tool to download windows 10 ISO, then modify ISO with anyburn and put answers file onto it. After that I run image on virtual machine, both Virtual box and VMware have the same problem.

could you please attach the screenshot of the error message.

**Comment by lukaszjakubiak** [comment]
> > I can confirm it persists after today's update.
> > I used windows download tool to download windows 10 ISO, then modify ISO with anyburn and put answers file onto it. After that I run image on virtual machine, both Virtual box and VMware have the same problem.
> 
> could you please attach the screenshot of the error message.

It was the same as the original error message on the screenshot that you posted.
You mentioned that's working now, so I am going make a test and give feedback.

**Comment by memstechtips** [comment]
@lukaszjakubiak Please don't use the Media Creation Tool to create the Bootable USB Drive. Follow the steps outlined in this [Tutorial Video](https://youtu.be/pDEZDD_gEbo) and it must work.

**Comment by bayssemir** [comment]
> > > I can confirm it persists after today's update.
> > > I used windows download tool to download windows 10 ISO, then modify ISO with anyburn and put answers file onto it. After that I run image on virtual machine, both Virtual box and VMware have the same problem.
> > 
> > could you please attach the screenshot of the error message.
> 
> It was the same as the original error message on the screenshot that you posted.
> You mentioned that's working now, so I am going make a test and give feedback.

sure, please keep in mind virtualbox on guided mode has an option to check the box for the skip unattended files option and i would like to inform you that you can check the box otherwise virtualbox creates another unattended xml file which might get clashes and not to run the desired xml
