### ISSUE TITLE
Solution for preventing to join workspace within microsoft apps

### ISSUE THREAD

**Issue by Syntax3rror404** [memstechtips/UnattendedWinstall#52]
Add this key to prevent windows to join a workspace when connecting for example with teams.

`reg.exe add "HKLM\SOFTWARE\Policies\Microsoft\Windows\WorkplaceJoin" /v BlockAADWorkplaceJoin /t REG_DWORD /d 1 /f`

Source: https://learn.microsoft.com/en-us/answers/questions/792235/windows-10-pop-up-message-to-allow-my-organization

**Comment by memstechtips** [comment]
Thanks, I will keep this issue open until I've added it.

**Comment by Syntax3rror404** [comment]
@memstechtips you fix windows :D Just amazing ^^

**Comment by memstechtips** [comment]
Added in https://github.com/memstechtips/UnattendedWinstall/commit/9f13a88f1c5291e348e7ad98c051a1fed5358497
