### ISSUE TITLE
Can't install 2024-07 Cumulative Update for Windows 11 Version 23H2 for x64-based Systems (KB5040442) | Using IoT-LTSC-Like

### ISSUE THREAD

**Issue by ASNXXXZ** [memstechtips/UnattendedWinstall#55]
**Hello, I'm getting now annoyed**, because every time I get to Widows Update in settings it shows this:
![image](https://github.com/user-attachments/assets/9b4aca58-2fa6-484a-85af-4892e1d53d3a)
And every time i restart my computer it doesn't dissappear... **Can someone help me?**

- Windows 11 2H23
- Unattended IoT-LTSC-Like

**Comment by memstechtips** [comment]
I know this isn't your exact issue, but there seems to be some issues with that update at the moment.
https://answers.microsoft.com/en-us/windows/forum/all/trouble-with-latest-cumulative-windows-july-2024/8d550379-3b6c-4290-bbef-276fbb17e0b3

You can also try pausing the updates for a week, and then immediately after that, resume the updates again.
Then check for updates and see if it installs then.

**Comment by ASNXXXZ** [comment]
Oh, thank you for telling me that! I paused these updates for now. Maybe I should also delete that cumulative windows July 2024 update?

**Comment by ASNXXXZ** [comment]
**UPDATE; After pausing and un-pausing, then downloading again it worked!**
![image](https://github.com/user-attachments/assets/1de4237a-cb91-42a8-866f-03de7aa9dddc)
