### ISSUE TITLE
Also remove windows Defender

### ISSUE THREAD

**Issue by NazmusSayad** [memstechtips/UnattendedWinstall#6]
This is the file that can remove Windows Defender:

[Generate autounattend.xml files for Windows 10/11, schneegans.de](https://schneegans.de/windows/unattend-generator/?LanguageMode=Unattended&UILanguage=en-US&UserLocale=en-US&KeyboardLayout=0409%3A00000409&GeoLocation=244&ProcessorArchitecture=amd64&ComputerNameMode=Random&TimeZoneMode=Implicit&PartitionMode=Interactive&WindowsEditionMode=Unattended&WindowsEdition=pro&UserAccountMode=Unattended&AccountName0=Admin&AccountPassword0=password&AccountGroup0=Administrators&AccountName1=User&AccountPassword1=password&AccountGroup1=Users&AutoLogonMode=Own&PasswordExpirationMode=Unlimited&LockoutMode=Default&DisableDefender=true&DisableDefenderPE=true&WifiMode=Interactive&ExpressSettings=DisableAll&WdacMode=Skip)

This is 100% working correctly...

---

I added all codes related to disabling Windows Defender from here to your answer file. Here is the final file:
[https://gist.github.com/NazmusSayad/55c788fa16729038f19416d283631c93](https://gist.github.com/NazmusSayad/55c788fa16729038f19416d283631c93)
*This just disables windows defender, nothing else*

Note: You can search `<!-- NEW: ` to find what I added.
![image](https://github.com/memstechtips/UnattendedWinstall/assets/87106526/84aed1ca-b13b-4fbf-b907-68b74793ccf7)

But this isn't working. This is giving this error:
![Screenshot (44)](https://github.com/memstechtips/UnattendedWinstall/assets/87106526/25b87285-fa6e-4758-8732-68476dca5981)

**Comment by memstechtips** [comment]
I've taken a look at your file and I'm not really sure why it's not working, but obviously there is an issue in the Windows PE phase according to your screenshot, or at least, something that's referenced in the Windows PE phase. I will see if I can make a separate file that removes defender or at least fix yours.

**Comment by NazmusSayad** [comment]
Sorry for this issue. I had installed an XML formatter in my VSCode. When saving the file, it was organizing the code and making the XML file unreadable by Microsoft. After disabling the formatter, everything is now working fine. However, formatting something shouldn't cause an error... I have no idea why.

**Comment by vuquangtrong** [comment]
@NazmusSayad I could not disable Windows Defender on Windows 11 24H2 image (I use UUP dump to make iso). On which version of Windows did you succesfully remove Defender?

**Comment by NazmusSayad** [comment]
> @NazmusSayad I could not disable Windows Defender on Windows 11 24H2 image (I use UUP dump to make iso). On which version of Windows did you succesfully remove Defender?

AutoAttend files doesn't work perfectly with unofficial or uupdump iso.
