### ISSUE TITLE
Winrar sometimes doesn't know if the file in the archive is packed.

### ISSUE THREAD

**Issue by Fleepe** [memstechtips/UnattendedWinstall#63]
I have never seen such a problem on a clean Windows 11. I tried to find what was causing this problem, I thought that maybe disableLastAccess 1 is the cause . But setting it to 2 did not solve the problem. Most likely some parameter is setting something wrong, but I'm not smart enough to figure out the cause of my problem.
![image](https://github.com/user-attachments/assets/5ac34b02-c250-4de6-b294-086bbd2cc637)
If necessary, I can install the English version of winrar to make it clearer for you.

**Comment by memstechtips** [comment]
Yes, please install English WinRAR and I will see if I can figure out where the issue might be.

**Comment by Fleepe** [comment]
![image](https://github.com/user-attachments/assets/524660da-7039-4c88-b950-8adb7e985aef)
Here is English version. This archive is different from the one above.

**Comment by Fleepe** [comment]
Although this is a minor problem that can be forgotten, it is still a problem. I use a slightly smaller autounattended file, which leaves some Windows applications and removes other tweaks, but even after checking it up and down, I still haven’t found the root of the problem. I'll leave this issue open for now, maybe someone will read it and understand why this is happening.

**Comment by Fleepe** [comment]
You live and learn. I asked the same question as here to the Winrar developer and there is his answer:
Some archive formats do not provide information about the packed size of a single file. In this case, WinRAR shows a question mark instead of the packed size. This does not mean that there is a problem with the archive.
