### ISSUE TITLE
Stuck in Windows 10 Login Screen, after first Update

### ISSUE THREAD

**Issue by nathanplenty** [memstechtips/UnattendedWinstall#65]
Aloha,

as mentioned in the title, after using "IoT-LTSC-Like" autounattend.xml file and installing windows 10, everything seems fine. Adjusted OS personal settings, connecting my Microsoft Account, prepared the rest of my drives and searching for new Updates (to get every driver for my hardware).

(Note, so just Windows stuff no new software installed)

But after the installation prompt asked me to restart, and the restart, I am stuck at the login screen without a password prompt. Common solutions (like CTRL + SHFT + DEL) won't work. Did every debug step twice, even re-configuarting the installation USB-Drive.

What did I miss?

**Comment by memstechtips** [comment]
Hi, this really shouldn't be happening and I'm not sure why it is happening. Have you tried booting from the Installation USB again, then clicking on "Repair your computer" to access the recovery settings and then uninstalling the updates, just to test?
