### ISSUE TITLE
WINGET not working after a fresh LTSC install

### ISSUE THREAD

**Issue by Szaamaan** [memstechtips/UnattendedWinstall#66]
WINGET, which can normally be used to install components, cannot be used in a Windows 11 instance created using the LTSC unattended XML.

The command is recognized but stops working almost instantly when performing any tasks.

The event log has the following:
```
Faulting application name: winget.exe, version: 1.17.2203.10001, time stamp: 0x622a8652
Faulting module name: WindowsPackageManager.dll, version: 1.17.2203.10001, time stamp: 0x622a8613
Exception code: 0xc0000005
Fault offset: 0x0000000000089bf3
Faulting process ID: 0x0x1FA4
Faulting application start time: 0x0x1DAD9BC61AC7605
Faulting application path: C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.17.10691.0_x64__8wekyb3d8bbwe\winget.exe
Faulting module path: C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.17.10691.0_x64__8wekyb3d8bbwe\WindowsPackageManager.dll
Report ID: 4dc06034-46a2-44e9-8ceb-ef2e2550484b
Faulting package full name: Microsoft.DesktopAppInstaller_1.17.10691.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: winget
```

**Comment by memstechtips** [comment]
Does it work on a default Windows 10 or Windows 11 install? Because there are no commands in the .XML file that explicitly influence WinGet as far as I know.

**Comment by Szaamaan** [comment]
> Does it work on a default Windows 10 or Windows 11 install? Because there are no commands in the .XML file that explicitly influence WinGet as far as I know.

Yeah, I've tried it immediately when I noticed this wasn't working. 

For reference, I did all my testing on a HyperV VM- one had a Windows 11 install using the official ISO with the `unattended.xml` provided by this project, the other was the install from the same ISO without the `XML` file.

**Comment by Tabada0** [comment]
Just finished a Windows 10 install and I'm facing the same issue.
I added a custom script to the desktop using winget to install a bundle of apps, and I'm not able to execute it because winget is not recognized as a command.

**Comment by Szaamaan** [comment]
> Just finished a Windows 10 install and I'm facing the same issue. I added a custom script to the desktop using winget to install a bundle of apps, and I'm not able to execute it because winget is not recognized as a command.

That... doesn't sound right. "Not recognized as a command" seems different from what I observed (the command was available but crashed on use), but then I was only testing on Windows 11...

**Comment by dineshmike** [comment]
Seems like this is due to the extremely old version of Winget and the CDN for that version has been deprecated. Winget is usually updated via Microsoft Store. Alternatively, it can be updated using the following command:
`Add-AppPackage https://aka.ms/GetWinGet`

**Comment by Szaamaan** [comment]
@dineshmike You're right! After updating the OS and Microsoft Store it works. So apparently the issue was somewhere between the keyboard and the chair. ;)
