### ISSUE TITLE
Taskbar searchbox removed all reg entries gone

### ISSUE THREAD

**Issue by PROJECT0770** [memstechtips/UnattendedWinstall#68]
Love this unattend file, the only issue is there's no taskbar searchbox available, I copied the registry entries from a Win10 Pro setup and tried to merge into a clean install (after the fact) and it won't accept it. I used cursor AI to scour the file and it couldn't find anything to take out to stop this from happening, so cursor wrote a few entries for me:

<File path="C:\Windows\Setup\Scripts\defaultuser.cmd">
  <![CDATA[
...
:: Shows Search Box on Taskbar
reg.exe add "HKU\DefaultUser\SOFTWARE\Microsoft\Windows\CurrentVersion\Search" /v SearchboxTaskbarMode /t REG_DWORD /d 2 /f
...
  ]]>
</File>
...

...

<File path="C:\Windows\Setup\Scripts\currentuser.cmd">
  <![CDATA[
...
:: Shows Search Box on Taskbar
reg.exe add "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Search" /v SearchboxTaskbarMode /t REG_DWORD /d 2 /f
...
  ]]>
</File>
...

That also would not fix it, I'm completely illiterate when it comes to any type of language (yes, even engrish)

Can someone please help with this, I need to make a clean disk from scratch and I'm using this unattend file to make the initial golden image, double clean.

I am aware there's an icon available that allows "click to search", but I like the text box and when clicked, shows all the past entries like "control panel" "regedit" "services.msc" etc.,
![TASKBAR SEARCH](https://github.com/user-attachments/assets/d3d493fe-9277-4af5-a7fc-b180032e88d9)

**Comment by ts0ra** [comment]
are you on windows 10?

**Comment by PROJECT0770** [comment]
Yes, Windows 10 Pro, I figured it out, took out Memory's taskbar mods and the setting of desktop to power mode and I was able to enable the search box afterwards.

Sent from Proton Mail Android

-------- Original Message --------

**Comment by memstechtips** [comment]
Glad you got it fixed!

**Comment by PROJECT0770** [comment]
BUT DID YOU FIND THE FIX?

Sent from Proton Mail Android

-------- Original Message --------

**Comment by PROJECT0770** [comment]
Not completed until you fix it.

Sent from Proton Mail Android

-------- Original Message --------

**Comment by memstechtips** [comment]
@PROJECT0770 
"Yes, Windows 10 Pro, I figured it out, took out Memory's taskbar mods and the setting of desktop to power mode and I was able to enable the search box afterwards."

You described this as the fix, so anyone having the same issue can fix it in this way. I'm not fixing it in the answer files, the search functions work fine for me, I don't want those recent items listed.
