### ISSUE TITLE
HEUR:Trojan.WinLNK.Alien.gen found in LAUNCH-CTT-WINUTIL.lnk

### ISSUE THREAD

**Issue by RomanSedykh** [memstechtips/UnattendedWinstall#70]
Kaspersky just found that few moments ago.

![image](https://github.com/user-attachments/assets/f09d80cd-aca6-4620-8ef7-9dbc47dc0541)

**Comment by DawieSonic** [comment]
https://github.com/ChrisTitusTech/winutil/issues/2433

See similar alert from Chris Titus Tech’s page

**Comment by memstechtips** [comment]
Thanks for this. I'm going to close this issue as it's something Chris Titus will have to fix. I see some people are reporting it as a false positive to their respective AV's. That's all you can do for now.
