### ISSUE TITLE
Only Windows 11 Home Edition available

### ISSUE THREAD

**Issue by MicaelJarniac** [memstechtips/UnattendedWinstall#74]
Related to #16.

On my Lenovo IdeaPad Gaming 3 laptop, only the Windows 11 Home Edition is available.

I wanted to install the Pro edition.

I believe this may be because the laptop originally came with it (I'm not entirely sure, as I've immediately installed Linux on it as soon as I got it).

On #16, it's said to have been fixed, but that doesn't seem to be the case, at least for me.

**Comment by memstechtips** [comment]
Hi there, when you get to that installation screen, just press the back button at the top left and continue with the setup. 
You will be able to select any version after that.
![image](https://github.com/user-attachments/assets/c48be1b6-c4c4-4d86-8ce6-aa6074dab53c)

**Comment by MicaelJarniac** [comment]
That did work! Thanks a lot! I'd have never guessed.

**Comment by memstechtips** [comment]
One of my Discord members told me about this method, didn't know about it either lol.
