### ISSUE TITLE
[Feature] Set Sound > Communications > Do nothing

### ISSUE THREAD

**Issue by MicaelJarniac** [memstechtips/UnattendedWinstall#76]
Under **System > Sound > More sound settings > Communications**, one can choose what happens when Windows detects communications activity, and by default, it's set to **"Reduce the volume of other sounds by 80%"**. This is one of the things that I manually set to **"Do nothing"** whenever I install Windows. It'd be cool to have this automated.

![image](https://github.com/user-attachments/assets/b16794ec-0d49-4796-8e29-fb101c61476f)

**Comment by MicaelJarniac** [comment]
I have absolutely no idea how to find that out, but will try.

**Comment by MicaelJarniac** [comment]
```
Registry Key    Change Type    Value Name    Value Data    Value Type    Data Length    Value Data Changed To    Value Type Changed To    Data Length Changed To    Key Modified Time 1    Key Modified Time 2    
HKEY_CURRENT_USER\Software\Microsoft\Multimedia\Audio    Modified Value    UserDuckingPreference    1    REG_DWORD    4    3    REG_DWORD    4    7/29/2024 12:20:48 PM    7/29/2024 12:21:02 PM
```
![image](https://github.com/user-attachments/assets/ec7fbd56-541e-4bf2-836a-fcf328c3194f)
![image](https://github.com/user-attachments/assets/a663eb9d-1c9c-4bc5-aabd-e73e98244bfb)

**Comment by vmserver** [comment]
> ```
> Registry Key    Change Type    Value Name    Value Data    Value Type    Data Length    Value Data Changed To    Value Type Changed To    Data Length Changed To    Key Modified Time 1    Key Modified Time 2    
> HKEY_CURRENT_USER\Software\Microsoft\Multimedia\Audio    Modified Value    UserDuckingPreference    1    REG_DWORD    4    3    REG_DWORD    4    7/29/2024 12:20:48 PM    7/29/2024 12:21:02 PM
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/19514231/353132917-ec7fbd56-541e-4bf2-836a-fcf328c3194f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MzQwMDUsIm5iZiI6MTcyMjQzMzcwNSwicGF0aCI6Ii8xOTUxNDIzMS8zNTMxMzI5MTctZWM3ZmJkNTYtNTQxZS00YmYyLTgzNmEtZmNmMzI4YzMxOTRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDEzNDgyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkMzMwOGE3ZDE1MTQ2ZmI4NjI2YjZkZTk1M2NlNjlmNmRiMWUwYmQ4MWRmNWU2NDgxMWZkNDM1OWMzZjNjNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NFmYtMoxsbbE53RrZZi7audaAx-N02vIs5HzrKY_sg4) ![image](https://private-user-images.githubusercontent.com/19514231/353133184-a663eb9d-1c9c-4bc5-aabd-e73e98244bfb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MzQwMDUsIm5iZiI6MTcyMjQzMzcwNSwicGF0aCI6Ii8xOTUxNDIzMS8zNTMxMzMxODQtYTY2M2ViOWQtMWM5Yy00YmM1LWFhYmQtZTczZTk4MjQ0YmZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDEzNDgyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3YjBmNzdjZGRhNjE3ZjVmNGZmNmZlMWUzMWY4MGUwNGI4MDBkODkyZGM0Y2MxNjZlMTQzY2NkYjRkMDI2OGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RrjW9KxNhW8pJKkCg7rm5xQA69EUKXLMwfjHL3B-GDs)



How did you able to find a reg entry for a manual change?

**Comment by MicaelJarniac** [comment]
> How did you able to find a reg entry for a manual change?

@vmserver I used [RegistryChangesView](https://www.nirsoft.net/utils/registry_changes_view.html) by NirSoft. It seems to be free, but I don't think it's open-source.

It was pretty intuitive, I just downloaded and ran it (no installation required). It then offered to take a registry snapshot from before the changes, to then compare with the registry after the changes.

**Comment by vmserver** [comment]
@MicaelJarniac Wow thats great, thanks for the info.

**Comment by memstechtips** [comment]
@MicaelJarniac Thanks, I will leave this issue open until I've tested it and added it to the answer files.

**Comment by memstechtips** [comment]
Added in https://github.com/memstechtips/UnattendedWinstall/commit/9f13a88f1c5291e348e7ad98c051a1fed5358497
