### ISSUE TITLE
Power button and lid switch are unresponsive

### ISSUE THREAD

**Issue by MicaelJarniac** [memstechtips/UnattendedWinstall#78]
I can't get the power button or the lid switch to do things like sleep or shut down.

**Comment by memstechtips** [comment]
Have you had a look at the advanced power settings in Control Panel? Is that what you're referring to?
![image](https://github.com/user-attachments/assets/c0f23bc5-ffdf-46d3-a597-b14673a6a95c)

**Comment by MicaelJarniac** [comment]
Yes, those are what's not working.

**Comment by MicaelJarniac** [comment]
Mine looks like this, and closing the lid or pressing the power button does nothing. The screen doesn't even turn off when closing the lid, I can see it's still on.
![image](https://github.com/user-attachments/assets/509125c5-1370-43b0-abb5-04ccd1e7afd6)

**Comment by MicaelJarniac** [comment]
I tried other options too, to see if it wasn't just "sleep" that wasn't working, and nothing did work.

**Comment by MicaelJarniac** [comment]
These seem to work on another laptop, so it might be a driver issue.

**Comment by memstechtips** [comment]
Allright, thanks for pointing that out, because I have also tested it on a laptop that I have here and the options do work correctly.
