### ISSUE TITLE
Add ARM support

### ISSUE THREAD

**Issue by omertrans678** [memstechtips/UnattendedWinstall#8]
Can you add ARM support Unattend config file?

**Comment by memstechtips** [comment]
That is something I can do in the future yeah, but don't expect anything soon.

**Comment by sigma2017** [comment]
This project is amazing, is the cleanest method out there to install a legit windows without all the bullshit included.
I just kept mspaint and notepad and also I let UAC enabled, other than that is perfect.
It will be a matter of time until windows ARM will become popular, compared to apple M chips is a bit disappointing.
Yes, in the future it will be useful but honestly, there is no rush at the moment.
Thanks again!

**Comment by memstechtips** [comment]
@omertrans678 Can you please test the following answer file on an ARM device please?

https://github.com/memstechtips/UnattendedWinstall/blob/development/IoT-LTSC-Like/arm64/autounattend.xml

Looking forward to your reply.

**Comment by BlackJoker90** [comment]
I just tested it successfully on my Mac with an M3 processor within Parallels Desktop. Everything works flawlessly. Thank you very much! You can go ahead and merge it into the main branch.

**Comment by BlackJoker90** [comment]
I found an issue: the Ethernet adapter is disabled, preventing the installation from completing once on the desktop. Could this be due to the Windows Updates being disabled? Where in the configuration can this be adjusted to ensure all updates are installed?

**Comment by memstechtips** [comment]
I'm not sure why it would be disabled because there are no entries that explicitly disable ethernet or any network settings for that matter.
Are you sure it's not a driver issue? You might need to install the correct driver for it to be detected. 

I've just updated the main branch, you are welcome to test out the new files.

**Comment by memstechtips** [comment]
Added ARM support in https://github.com/memstechtips/UnattendedWinstall/commit/a9348a19ad425bb840c2a3e4e67501a81715ef66
