### ISSUE TITLE
Unable to start vmware virtual machines

### ISSUE THREAD

**Issue by clementchong** [memstechtips/UnattendedWinstall#80]
Thank you for sharing this in clear steps for the good of the community! It was pretty straightforward to get the debloated windows 11 running with much lower process count and memory usage!

I have one observation, not sure if this is the right place. After the new debloated Windows is running smoothly, I installed the vmware workstation pro 17 on it for personal use and reuse the same debloated windows iso as the OS for my virtual machine (vm).

vmware software installed fine but I was not able to start up the new vm. It raised error 0xc00007b which I searched and tried to install .Net framework, Visual Studio C++ redistributable packages but still no go.

If I install the same vmware on a normal windows OS and setup new VM with debloated windows, it works. The only difference is base OS if it is debloated or not.

On the debloated base OS, i can setup vm with debloated vm using VirtualBox. Therefore, I am thinking the debloated Windows is missing something required for the vmware to start up the vm.

I have been trying to find a solution but unsuccessful. Thank you for listening.

**Comment by memstechtips** [comment]
Hi there,

I'm using VMWare Workstation Pro on the Standard `xml` version on Windows 11 and don't have any of those issues.
The fact that VirtualBox works means that your virtualization is enabled, so it must be some sort of other issue.

Do you still get the 0xc00007b error when trying to start the VM?

**Comment by memstechtips** [comment]
I'm sorry but I'm not sure why you're having this issue. I'm using VMware without any issues, I don't think it is related to the answer file.
