### ISSUE TITLE
OneDrive broken

### ISSUE THREAD

**Issue by vasendak** [memstechtips/UnattendedWinstall#83]
I installed IoT-LTSC-Like version. I use OneDrive and wanted to install it afterwards but it just refuses to run. Is there a way to fix this?

**Comment by Sonnyhood** [comment]
same issue here, something to do with MS store perhaps i saw an error, it tried to load a link like appx, only flashed up a second.
Perhaps we need edge and store to run this?

**Comment by vasendak** [comment]
I actually have the version with the MS store and I can install the app from there, but it doesn't sync in File Explorer which I actively use. I downloaded the application and it installs but doesn't run. While it is installing, a OneDrive folder shows on File Explorer and immediately disappears.

**Comment by memstechtips** [comment]
Hey there,

You can find the fix here
https://discord.com/channels/1192038830245679177/1259594891499929750

Kind Regards
Mem

**Comment by 7ergei** [comment]
Hi, same issue - please post a solution here...

**Comment by memstechtips** [comment]
Hi there, glad you like it! I assume you already have it installed though.
In that case you also need to delete these entries.
```
:: Disables OneDrive Automatic Backups of Important Folders (Documents,
Pictures etc.)
reg.exe add "HKLM\SOFTWARE\Policies\Microsoft\OneDrive" /v KFMBlockOptIn /t
REG_DWORD /d 1 /f
reg.exe add "HKLM\SOFTWARE\Policies\Microsoft\Windows\OneDrive" /v
DisableFileSyncNGSC /t REG_DWORD /d 1 /f
```

```
:: Disables User Account Sync
reg.exe add
"HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Privacy" /v
SettingSyncEnabled /t REG_DWORD /d 0 /f
```
After doing that and restarting the computer it should work then.

I copied that directly from discord. See if it works?

**Comment by vasendak** [comment]
Thank you boss, will try it in couple of hours when I get home.
Thank you for the wonderful work and the support you provide!

**Comment by 7ergei** [comment]
Indeed, downloading OneDriveSetup.exe from Microsoft and making Registry tweaks fixed the problem and OneDrive is alive!

I've written a reg files for anyone who would like to - https://1drv.ms/f/s!AgnT4EEG38LNkKNZMvwH9Lm_cX7G8Q?e=hn1FLC

Here are the steps to follow:
1) Download OneDrive from Microsoft and install it, it takes a couple of min to finish.
2) Run reg file from CMD.
![01](https://github.com/user-attachments/assets/97d4123c-1200-4f64-b2d4-75ebf6c3da78)
![02](https://github.com/user-attachments/assets/c9fe04c4-c591-497d-9a03-53a35116b4fa)
3) Reboot and start use OneDrive again ;-)

**Comment by vasendak** [comment]
Wow, tested it now. Works perfectly 😁

**Comment by 7ergei** [comment]
Agreed ;-)
https://github.com/7ergei/OneDrive_IoT-LTSC
