### ISSUE TITLE
Can't add more microsoft account to edge 

### ISSUE THREAD

**Issue by NguyenMinhDDuc** [memstechtips/UnattendedWinstall#84]
<img width="768" alt="Untitled" src="https://github.com/user-attachments/assets/cc6d22c3-2478-4dcd-a931-6906e95e6d53">

**Comment by memstechtips** [comment]
It's most probably due to some services and telemetry that might be disabled.
This is on the LTSC like version right?

**Comment by NguyenMinhDDuc** [comment]
Yes it's LTSC like ver

**Comment by PantiesIsStoopid** [comment]
To fix the “Something went wrong while registering for Windows Hello” error, the most likely cause, especially on an LTSC version of Windows, is that some required services and telemetry may be disabled. To resolve this, you can ensure the following services are enabled:

	1.	Windows Biometric Service - This service is required for biometric authentication like fingerprint or facial recognition.

	2.	Windows Hello Face Authentication Service - If using facial recognition, ensure this service is running.

	3.	Windows Update Service - For certain features of Windows Hello, updates may need to be downloaded.

	4.	Device Management Enrollment Service - Used to manage and enroll devices for Windows Hello.

	5.	Windows Push Notification Service (WNS) - Required for certain account and Hello features.

Check the status of these services via the Services app (services.msc), and set their startup type to Automatic if they are disabled.

**Comment by memstechtips** [comment]
Thanks for your input @PantiesIsStoopid 

I'm closing the issue as no further replies from OP has been received.
