### ISSUE TITLE
No network after waking up from sleep

### ISSUE THREAD

**Issue by MwGLTike** [memstechtips/UnattendedWinstall#85]
A rare occurrence happens where I get no network activity after waking up my computer from sleep/hibernation. I am using the LTSC version of the XML. I have not tried to see if my wireless works, but, my wired connection does not when this occurs.

**Comment by memstechtips** [comment]
That's odd, I haven't seen that happen yet.
Can you check this setting in the Device Manager for your LAN Adapter?
![image](https://github.com/user-attachments/assets/4911a54d-9bed-4e27-bc14-52bf305be6c8)

Make sure that it's not enabled.

**Comment by memstechtips** [comment]
@MwGLTike Any update on this?
