### ISSUE TITLE
Dual Monitor Support and defaultuser script sometimes doesn't pop up after install

### ISSUE THREAD

**Issue by nickmouaikel** [memstechtips/UnattendedWinstall#9]
Hello, I have probably installed this ISO at least 10 times now, through virtual machines and various old pieces of hardware. The first installs were fine, everything was fine, the default user script ran through the script and restarted and I was able to connect a second monitor. After testing on various VMs and PCs, it seems that it is hit or miss if the defaultuser script will show up after first logon, however the computer still restarts. I would like to eventually install this debloated ISO on my main PC with 2 monitors. When I check the display settings, windows doesn't detect the second monitor. I wonder if some changes in the registry are causing this, but I doubt it because it worked fine at least once before.

Just an observation I noticed.

**Comment by memstechtips** [comment]
Thanks for reporting your observations!
You can go to the following filepath C:\Windows\Setup\Scripts (You might have to enable Hidden files & Folders) and then you can look at the log files there with Notepad or Notepad++ if you want to download that. If there is a "currentuser.log" file, it means the currentuser entries did in fact run correctly, but you can open the file to view the details of each registry tweak.

As for the second monitor, I'm currently using the answer file on 2 computers with dual monitor setups (Work and Home PC) and it's working perfectly fine for me, but the 2nd monitor isn't always visible right after installing Windows. I have to install the Nvidia Graphics Driver for my GPU first before I get to see the second monitor, that is normal. But if you have all of your graphics drivers up to date and it's still not showing, then there's something wrong.

**Comment by nickmouaikel** [comment]
2 monitor thing fixed with driver updates, I will look into the logs. Thanks!
