### ISSUE TITLE
how to get back Microsoft store

### ISSUE THREAD

**Issue by iamthelara** [memstechtips/UnattendedWinstall#91]
hey, I applied your script IoT-LTSC-Like but I can't find Microsoft store. I am new to this. Please help me.

**Comment by vmserver** [comment]
@iamthelara Try downloading [THIS](https://pixeldrain.com/u/GBQsXJ6q) and double click, also update it after installation.

**Comment by iamthelara** [comment]
Do you have any solution for Grneric Bluetooth adapter driver is not working? I have tried most of the solution available on internet. Suggest me any.

**Comment by iamthelara** [comment]
@vmserver ?

**Comment by iamthelara** [comment]
please?

**Comment by iamthelara** [comment]
@vmserver ?

**Comment by iamthelara** [comment]
Thanks dev. I am having Bluetooth problem now. Do you have any solution?

**Comment by vmserver** [comment]
@iamthelara Which Bluetooth adapter are you using? write down the code written on it.

**Comment by iamthelara** [comment]
> @iamthelara Which Bluetooth adapter are you using? write down the code written on it.

I am not using any adapter the driver's name is generic bluetooth adapter.
![20240801_135722](https://github.com/user-attachments/assets/c8ef2e31-c7ab-45cf-8c51-1b95f2d58e0a)

**Comment by ffiesta** [comment]
Hi, i don't have sure, but if you go to drivers, garb id off device you can check on internet for that driver, or you go to device, desktop or laptop reseller check the specs and download the driver.

**Comment by iamthelara** [comment]
> Hi, i don't have sure, but if you go to drivers, garb id off device you can check on internet for that driver, or you go to device, desktop or laptop reseller check the specs and download the driver.

Okay ,thanks

**Comment by memstechtips** [comment]
To reinstall the Microsoft Store, please see https://github.com/memstechtips/UnattendedWinstall/blob/main/TROUBLESHOOTING.md

With regards to the Bluetooth, ensure you have the correct drivers installed. This guide can also help https://youtu.be/4uxQbxcxkBg

**Comment by julianpoemp** [comment]
> [@iamthelara](https://github.com/iamthelara) Try downloading [THIS](https://pixeldrain.com/u/GBQsXJ6q) and double click, also update it after installation.

Thank you, this helped me a lot! Installing using UWScript didn't work for me....
