### ISSUE TITLE
Xbox game bar not working properly

### ISSUE THREAD

**Issue by TheSupremeCheeseMaker** [memstechtips/UnattendedWinstall#96]
So I have been using the windows 10 unattendedWinstall standart version for a few days and noticed that game bar was not working properly. after a hour of trying every single probable solution I saw on reddit and youtube I could get a somehow working game bar but it does not quite work properly. like when I try to enable game bar from windows settings it just disables itself, I can not open it with the shortcut, video capture not available and notifications not showing up. I turned on notifications, background apps and tried registry editor but still did not work.

**Comment by memstechtips** [comment]
Hi there, please follow the steps outlined here: https://github.com/memstechtips/UnattendedWinstall/blob/main/TROUBLESHOOTING.md

One of my Discord members had the same issue and said it is working perfectly after following these instructions.
![image](https://github.com/user-attachments/assets/7cda2948-bd48-40e9-b1f0-374c75a7e05d)
