### ISSUE TITLE
How to get back some original apps

### ISSUE THREAD

**Issue by JXRNO** [memstechtips/UnattendedWinstall#97]
Hello,

I've tried to modify your Standard version of the script, and removed line 400 which is the line to delete Notepad, and that works. When installing it comes with Notepad.

However when I try this with the calculator, camera, alarm (clock), paint, it doesn't seem to work and is not installed.

Also it still installs the old calculator instead of the new one from Windows 10 even though I removed the line to delete calculator.

When pressing Windows + R and typing 'mspaint' it says it can't be found so it's not hidden I believe. For some reason the "Getting Started" app seems to get installed even though I never removed that line.

I am on Windows 11 IoT Enterprise LTSC 24H2.

Are there any solutions?

**Comment by memstechtips** [comment]
Hi there,

I haven't tested the file(s) on IoT Enterprise LTSC versions and also not on 24H2. I mention this in the README as well.
You can compare my IoT-LTSC version with the Standard version and see that I removed the lines in the IoT-LTSC version for apps like Notepad, Paint, Calculator etc. and those are installed when using a Pro or Home version of Windows, I'm not sure if it's different for the Enterprise versions of Windows.

As for the "Getting Started" app, there is no way to remove it that I've found.
