### ISSUE TITLE
Stuck On 'Getting Ready' screen during Windows 11 Install.

### ISSUE THREAD

**Issue by KedarWolf** [memstechtips/UnattendedWinstall#99]
I tried two different Windows 11 ISOs, never gets past the Getting Ready screen. An older version of the answer file I tried a few weeks ago worked just fine.

**Comment by memstechtips** [comment]
Which version of the file are you using?

I've used both the Core and LTSC like versions on three different computers in the past 2 days, didn't have any issues.

**Comment by KedarWolf** [comment]
I use the newest LTSC like version answer file on a 10.0.22635.4005 IOT Enterprise ISO made from the UUP Dump website.

**Comment by KedarWolf** [comment]
I used it on this kind of ISO before, but I think for some reason Github wasn't allowing me to properly download the answer file.

I downloaded it again and now it looks okay. I'll test it again.

**Comment by memstechtips** [comment]
Allright, hopefully all goes well.

**Comment by silviodonlic** [comment]
@KedarWolf Is there a solution/conclusion?
I've had the same "stuck on Getting Ready" problem with Win11 setup, although not the original, but tempered with.

Interesting thing: the pre-latest standard xml installed in half an hour, windowse opened and running fine. 
Not sure if the scripts were executed there bc there was Edge in toolbar.

**Comment by memstechtips** [comment]
I've used the unedited answer file to install Windows 11 on multiple different computers (laptops and desktops) without any issues since the creation of this issue. I don't believe there is any issue in the unedited file.
